spring.application.name=oposiciones
#spring.sql.init.mode=always


# H2 - Crea la carpeta data automática y genera los archivos de la base de datos
spring.datasource.url=jdbc:h2:file:./data/oposicionesdb;MODE=MySQL
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Para crear automáticamente las tablas
#cambiar none-update segun si estamos trabajando con los usuarios
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Para mostrar en consola
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Para que ejecute schema.sql y data.sql
spring.jpa.defer-datasource-initialization=true

# subida archivos
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB

# carpeta uploads
file.upload-dir=uploads


