spring.application.name=oposiciones
spring.sql.init.mode=never
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

# H2
spring.datasource.url=jdbc:h2:file:./data/oposicionesdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# H2 console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# subida archivos
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB

# carpeta uploads
file.upload-dir=uploads
